name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - '*.*.*'

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: build
      uses: docker/setup-buildx-action@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64, linux/arm64/v8, linux/arm/v7
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/wolzz:${{ github.ref_name }}
          ${{ secrets.DOCKERHUB_USERNAME }}/wolzz:latest
