name: Multi Platform Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify the Tag for this Release'
        required: true
      version:
        description: 'Enter the Version for this Release'
        required: true
      body:
        description: 'Enter the Body for this Release'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Go mod init
      run: go mod init wolzz

    - name: Go mod tidy
      run: go mod tidy

    - name: Build for Linux amd64
      run: |
        mkdir -p build/wolzz_linux_amd64
        GOARCH=amd64 GOOS=linux go build -o build/wolzz_linux_amd64/wolzz -v .
        cp -R index.html devices.json config.json users.json static build/wolzz_linux_amd64/

    - name: Build for Linux arm64
      run: |
        mkdir -p build/wolzz_linux_arm64
        GOARCH=arm64 GOOS=linux go build -o build/wolzz_linux_arm64/wolzz -v .
        cp -R index.html devices.json config.json users.json static build/wolzz_linux_arm64/

    - name: Build for Windows amd64
      run: |
        mkdir -p build/wolzz_windows_amd64
        GOARCH=amd64 GOOS=windows go build -o build/wolzz_windows_amd64/wolzz.exe -v .
        cp -R index.html devices.json config.json users.json static build/wolzz_windows_amd64/

    - name: Build for Windows arm64
      run: |
        mkdir -p build/wolzz_windows_arm64
        GOARCH=arm64 GOOS=windows go build -o build/wolzz_windows_arm64/wolzz.exe -v .
        cp -R index.html devices.json config.json users.json static build/wolzz_windows_amd64/

    - name: Create Archive for Linux amd64
      run: tar -czvf build/wolzz_linux_amd64.tar.gz -C build/wolzz_linux_amd64 .

    - name: Create Archive for Linux arm64
      run: tar -czvf build/wolzz_linux_arm64.tar.gz -C build/wolzz_linux_arm64 .

    - name: Create Archive for Windows amd64
      run: cd build/wolzz_windows_amd64
      run: zip -r ../../build/wolzz_windows_amd64.zip ./

    - name: Create Archive for Windows arm64
      working-directory: ${{ github.workspace }}
      run: cd build/wolzz_windows_armd64
      run: zip -r ../../build/wolzz_windows_arm64.zip ./
      run: cd ../..

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/wolzz_linux_amd64.tar.gz
          build/wolzz_linux_arm64.tar.gz
          build/wolzz_windows_amd64.zip
          build/wolzz_windows_arm64.zip
        token: ${{ secrets.GH_TOKEN }}
        tag_name: ${{ github.event.inputs.tag }}
        name: ${{ github.event.inputs.version }}
        body: ${{ github.event.inputs.body }}
