name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Specify the version for the release'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Go mod init
      run: go mod init

    - name: Go mod tidy
      run: go mod tidy

    - name: Build
      run: go build -o wolweb -v .

    - name: Create Archive
      run: |
        tar -czvf wolweb.tar.gz wolweb index.html devices.json config.json users.json static
      working-directory: ${{ github.workspace }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: wolweb.tar.gz
        github_token: ${{ secrets.GH_TOKEN }}